export {ConfigurationOptions, HTTPOptions} from './config-base';
export {Credentials} from './credentials';
export {CredentialProviderChain} from './credentials/credential_provider_chain';
export {Endpoint} from './endpoint';
export {AWSError} from './error';
export {HttpRequest} from './http_request';
export {HttpResponse} from './http_response';
export {Request} from './request';
export {Response} from './response';
export {Service} from './service';
