apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: loopback4-notifications
  annotations:
    github.com/project-slug: sourcefuse/loopback4-notifications
  namespace: arc
  description: LoopBack 4 extension for setting up various notification mechanisms in loopback4 application, vis-a-vis, Push notification, SMS notification, Email notification.
  tags:
    - notifications
    - email
    - sms
    - loopback
    - extension
  links:
    - url: https://npmjs.com/package/loopback4-notifications
      title: NPM Package
    - url: https://loopback.io/doc/en/lb4/Extending-LoopBack-4.html#overview
      title: Extending LoopBack
spec:
  type: component
  lifecycle: production
  owner: sourcefuse
